BattleShip/BattleShip.WEB/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BattleShip.Models.Entities;
using BattleShip.WEB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using BattleShip.BusinessLogic.Interfaces;
using AutoMapper;

namespace BattleShip.WEB.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private IGameService gameService;

        public GameController(IGameService service)
        {
            this.gameService = service;
        }

        public IActionResult CreateGame()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateGame([FromBody] ShipViewModel[] shipsView)
        {
            int playerid = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ShipViewModel, Ship>()).CreateMapper();
            var ships = mapper.Map <IEnumerable<ShipViewModel>, List<Ship>>(shipsView);
            int gameId = this.gameService.CreateGame(playerid);
            int fieldId = this.gameService.CreateField(playerid, gameId);
            this.gameService.AddShipsToField(fieldId, ships);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult FindGame([FromBody] ShipViewModel[] shipsView)
        {
            int playerid = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ShipViewModel, Ship>()).CreateMapper();
            var ships = mapper.Map<IEnumerable<ShipViewModel>, List<Ship>>(shipsView);
            int fieldId = this.gameService.CreateField(playerid, null);
            this.gameService.AddShipsToField(fieldId, ships);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Game(int id)
        {
            int playerid = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            ViewBag.PlayerId = playerid;
            ViewBag.GameId = id;
            var game = this.gameService.GetGame(id);
            ViewBag.CurrentMove = game.CurrentMovePlayerId;
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<Move, RecordsView>()).CreateMapper();
            var records = mapper.Map<IEnumerable<Move>, List<RecordsView>>(this.gameService.GetAllRecords(id));
            return View(records);
        }

        [HttpGet]
        public JsonResult GetMyCoordinates(int id)
        {
            int playerid = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<Coordinate, CoordinateView>()
            .ForMember("HaveShip", opt => opt.MapFrom(c => c.Ship != null))).CreateMapper();
            var coord = this.gameService.GetCoordinatesForGame(playerid, id);
            var coordinates = mapper.Map<IEnumerable<Coordinate>, List<CoordinateView>>(coord);
            return Json(coordinates);
        }

        [HttpGet]
        public JsonResult GetEnemyCoordinates(int id)
        {
            int playerid = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));            
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<Coordinate, CoordinateView>()
            .ForMember("HaveShip", opt => opt.MapFrom(c => c.Ship != null))).CreateMapper();
            var coord = this.gameService.GetCoordinatesForGame(playerid, id, false);
            var coordinates = mapper.Map<IEnumerable<Coordinate>, List<CoordinateView>>(coord);
            return Json(coordinates);
        }
    }
}

BattleShip/BattleShip.WEB/Controllers/PersonalAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BattleShip.BusinessLogic.Interfaces;
using BattleShip.WEB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BattleShip.WEB.Controllers
{
    [Authorize]
    public class PersonalAccountController : Controller
    {
        IGameService gameService;
        IPlayerService playerService;

        public PersonalAccountController(IGameService gameService, IPlayerService playerService)
        {
            this.gameService = gameService;
            this.playerService = playerService;
        }

        public IActionResult MyAccount()
        {
            int playerid = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            ViewBag.PlayerId = playerid;
            var games = this.gameService.GetPlayerGames(Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier)));
            PersonalAccountViewModel personalAccountView = new PersonalAccountViewModel { UserName = this.playerService.FindPlayer(playerid).UserName, Games = games };
            return View(personalAccountView);
        }
    }
}

BattleShip/BattleShip.WEB/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BattleShip.BusinessLogic.Enums;
using BattleShip.BusinessLogic.Interfaces;
using BattleShip.WEB.Models;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace BattleShip.WEB.Controllers
{
    public class StatisticsController : Controller
    {
        IStatisticsService statisticsService;

        public StatisticsController(IStatisticsService statisticsService)
        {
            this.statisticsService = statisticsService;
        }

        public IActionResult Statistics(int page = 1, string name = "", bool onlyIntactShips = false, FilterMoveState filterMoveState = FilterMoveState.All, SortState sortOrder = SortState.NameAsc)
        {
            int pageSize = 3;
            var records = this.statisticsService.GetStatisticsRecords(name, onlyIntactShips, sortOrder, filterMoveState);
            var count = records.Count();
            var items = records.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            StatisticsViewModel viewModel = new StatisticsViewModel
            {
                PageViewModel = new PageViewModel(count, page, pageSize),
                StatisticsRecords = items,
                SortedStatisticsRecord = new SortedStatisticsRecord(sortOrder),
                FilterStatisticsRecord = new FilterStatisticsRecord(name, filterMoveState, onlyIntactShips)
            };

            return View(viewModel);
        }
    }
}

BattleShip/BattleShip.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BattleShip.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BattleShip.WEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                            </li>
                        }

                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="CreateGame">Играть</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PersonalAccount" asp-action="MyAccount">Мои игры</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Statistics">Статистика по играм</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BattleShip.WEB - <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html >